In [2]:
# ===================================
# Bidirectional Associative Memory (BAM)
# ===================================
import numpy as np

# ===================================
# 1. Define Bipolar Patterns (Set A and Set B)
# ===================================
# (Use -1 and +1 as in manual)

# Set A (Input patterns)
X = np.array([
    [1, 1, 1],
    [-1, -1, -1]
])

# Set B (Target patterns)
Y = np.array([
    [1, 1, 1, 1, 1, 1],
    [-1, -1, -1, -1, -1, -1]
])

# ===================================
# 2. Initialize Weight Matrix
# ===================================
W = np.zeros((X.shape[1], Y.shape[1]))

# Training using outer product rule
for i in range(len(X)):
    W += np.outer(X[i], Y[i])

print("Weight Matrix:\n", W)

# ===================================
# 3. Activation Function
# ===================================
def activation(x):
    return np.where(x >= 0, 1, -1)

# ===================================
# 4. Testing (Forward + Backward until convergence)
# ===================================
x_test = np.array([1, 1, 1])   # Test input

print("\nInitial Input:", x_test)

prev_x = np.zeros_like(x_test)

while not np.array_equal(x_test, prev_x):
    prev_x = x_test.copy()

    # Forward pass (X → Y)
    y_out = activation(np.dot(x_test, W))

    # Backward pass (Y → X)
    x_test = activation(np.dot(y_out, W.T))

print("\nFinal Output (Y):", y_out)
print("Recalled Input (X):", x_test)

Weight Matrix:
 [[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]

Initial Input: [1 1 1]

Final Output (Y): [1 1 1 1 1 1]
Recalled Input (X): [1 1 1]
